version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:16-alpine
    container_name: drone_fleet_db
    environment:
      POSTGRES_DB: drone_fleet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5512
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - drone-network

  # Redis Cache Service for real-time state
  redis:
    image: redis:7-alpine
    container_name: drone_fleet_redis
    ports:
      - "6379:6379"
    networks:
      - drone-network

  # Spring Boot Application Service
  app:
    build: .
    container_name: drone_fleet_app
    ports:
      - "8080:8080"
    environment:
      # These environment variables override application.properties inside the container
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/drone_fleet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 5512
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - drone-network

volumes:
  pgdata:

networks:
  drone-network:
    driver: bridge