package com.sosag.dronefleet.controller;

import com.sosag.dronefleet.dto.DroneRequestDTO;
import com.sosag.dronefleet.dto.DroneResponseDTO;
import com.sosag.dronefleet.model.Drone;
import com.sosag.dronefleet.model.DroneModel;
import com.sosag.dronefleet.repository.DroneModelRepository;
import com.sosag.dronefleet.service.DroneService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST controller for managing Drone resources.
 *
 * <p>Exposes endpoints to create, retrieve, and list drones within the fleet.</p>
 */
@RestController
@RequestMapping("/api/v1/drones")
public class DroneController {

    private final DroneService droneService;
    private final DroneModelRepository droneModelRepository;

    /**
     * Constructs a DroneController with the required dependencies.
     *
     * @param droneService the service handling drone business logic
     * @param droneModelRepository the repository for drone model data
     */
    public DroneController(DroneService droneService, DroneModelRepository droneModelRepository) {
        this.droneService = droneService;
        this.droneModelRepository = droneModelRepository;
    }

    /**
     * Retrieves all drones registered in the system.
     *
     * @return a list of DroneResponseDTO objects
     */
    @GetMapping
    public ResponseEntity<List<DroneResponseDTO>> getAllDrones() {
        List<Drone> drones = droneService.getAllDrones();
        List<DroneResponseDTO> response = drones.stream()
                .map(DroneResponseDTO::fromEntity)
                .toList();
        return ResponseEntity.ok(response);
    }

    /**
     * Retrieves a specific drone by its technical identifier.
     *
     * @param id the technical identifier of the drone
     * @return the DroneResponseDTO if found
     */
    @GetMapping("/{id}")
    public ResponseEntity<DroneResponseDTO> getDroneById(@PathVariable Long id) {
        Drone drone = droneService.getDroneById(id);
        return ResponseEntity.ok(DroneResponseDTO.fromEntity(drone));
    }

    /**
     * Creates and registers a new drone in the fleet.
     *
     * <p>The serial number is automatically generated by the system.
     * The drone model must exist in the database.</p>
     *
     * @param request the DTO containing the drone creation data
     * @return the created DroneResponseDTO with HTTP 201 Created status
     */
    @PostMapping
    public ResponseEntity<DroneResponseDTO> createDrone(@Valid @RequestBody DroneRequestDTO request) {
        DroneModel droneModel = droneModelRepository.findById(request.droneModelId())
                .orElseThrow(() -> new IllegalArgumentException("Drone model not found with id: " + request.droneModelId()));

        Drone newDrone = new Drone();
        newDrone.setDroneModel(droneModel);
        newDrone.setStatus(request.status());
        newDrone.setBatteryLevel(request.batteryLevel());
        newDrone.setTotalFlightHours(request.totalFlightHours());

        Drone savedDrone = droneService.createDrone(newDrone);
        return ResponseEntity.status(HttpStatus.CREATED).body(DroneResponseDTO.fromEntity(savedDrone));
    }
}